# Generated by Django 5.2.17 on 2026-09-28 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('owner', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(default=dict)),
                ('graph_data', models.JSONField(default=dict)),
                ('smells', models.JSONField(default=list)),
                ('guide_markdown', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('parsing', 'Parsing'), ('analyzing', 'Analyzing'), ('ai', 'AI enrichment'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='repositories.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
